[package]
name = "lark-pkg"
description = "Dependency resolution and fetching for Lark packages."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
semver = { version = "1.0.28", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.4"

[lints]
workspace = true
